---
title: "Knorr_Held_basic"
author: "Jostein Aasteboel, Aanes"
date: "2023-09-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#Load libraries
library(INLA)
library(tidyverse)
```

```{r load_data}
#Areas in Ohio, needed for adjacency matrix
ohio_graph_path <- "ohioadj.asc"

#Load data
raw_df <- read.table("http://faculty.washington.edu/jonno/SISMIDmaterial/ohiodata2_spacetime.txt",header=T)
head(raw_df)
```

```{r data_formatting}
n <- length(unique(raw_df$county))   # Number of areas
T <- length(unique(raw_df$time))     # Number of time points

#Format data for INLA
ohio_df <- data.frame(county = raw_df$county,
                      year = raw_df$time,
                      expected = raw_df$E,
                      deaths = raw_df$Y)

#Create copies of time for unstructured/structured random effects
ohio_df$time.unstructured <- ohio_df$time.structured <- ohio_df$year

head(ohio_df)
```

```{r Adjacency_matrix}
#Load the adjacency file
adjacency <- read.table(ohio_graph_path, header = T)

#Find how many areas are contiguous to each area
n_i = adjacency$num

#Making the adjancency matrix, referred to as K_theta
#----------------------------------------------------
K_theta = diag(n)       # Making a sparse nxn matrix
diag(K_theta) = n_i     # Insert n_i into diagonal

for(i in 1:n){ 
  #For each county i, find out which counties are contiguous
  adjacent_i <- adjacency[i, 3:ncol(adjacency)][adjacency[i,3:ncol(adjacency)]!=0]

  #Insert into structure matrix which areas are contiguous
  K_theta[i, adjacent_i] = -1
}
#----------------------------------------------------

#Sanity check: If K_theta is correct both rows and columns should all sum-to-zero
print("rows sum-to-zero:")
print((length(unique(apply(K_theta, 1, sum))) == 1 & apply(K_theta, 1, sum)[1] == 0))

print("columns sum-to-zero:")
print((length(unique(apply(K_theta, 2, sum))) == 1 & apply(K_theta, 2, sum)[1] == 0))
```

```{r RW_precision_matrices}
#Precision matrices for random walk 1 and 2
prec_RW1 <- INLA:::inla.rw(n = T, order = 1, 
                           scale.model = FALSE, # set scale.model  = F because we'll scale in the formula
                           sparse = TRUE)

prec_RW2 <- INLA:::inla.rw(n = T, order = 2, 
                           scale.model = FALSE, # set scale.model  = F because we'll scale in the formula
                           sparse = TRUE)
```

```{r Basic_linear_predictor}
#Basic linear predictor of, alpha assumed RW1
basic_linear_predictor <- deaths ~ 1 + f(year, 
                                         model = "bym2",
                                         scale.model = T, 
                                         constr = T, 
                                         rankdef = 1,
                                         graph = prec_RW1,
                                         hyper = list(
                                              phi = list(
                                                prior = "pc",
                                                param = c(0.5, 2/3)), #Magic number
                                              prec = list(
                                                prior = "pc.prec",
                                                param = c(1, 0.01)) #Magic number
                                              )
                                         ) + 
                                        f(county, 
                                          model = "bym2",
                                          scale.model = T,
                                          constr = T,
                                          rankdef = 1,
                                          graph = K_theta,
                                          hyper = list(
                                            phi = list(
                                              prior = "pc",
                                              param = c(0.5, 2/3) #Magic number
                                            ),
                                            prec = list(
                                              prior = "pc.prec",
                                              param = c(1, 0.01) #Magic number
                                            )
                                          ))
```

```{r fit_basic_linear_predictor}
basic_model_fit <- inla(basic_linear_predictor,
                 data = ohio_df,
                 family = "poisson",
                 E = expected,
                 control.compute = list(config = TRUE)) # needed if you want to see constraints later
```

```{r summary_basic}
summary_basic_fit <- summary(basic_model_fit)


print("---")
print(summary_basic_fit$hyperpar)
print("---")
print(summary_basic_fit$linear.predictor)
print("---")
print(summary_basic_fit$fixed)
print("---")
print(summary_basic_fit$mlik)
```
```{r type_I_interaction}
# a unique number for each time.space combination (88*21 = 1848)
ohio_df$spacetime.unstructured <- 1:(n * T)

# Add Type I Interaction term to basic linear predictor
lin_pred_w_type_I <- update(basic_linear_predictor, ~. + 
                              f(spacetime.unstructured, model="iid", 
                                hyper = list(
                                  prec = list(
                                    param = c(1, 0.01))
                                  )
                                ))

#Assuming fully connected adjacency structure (e.g no islands) 
#when defining rank-deficiency
type_I_fit <- inla(lin_pred_w_type_I,
                 data = ohio_df,
                 family = "poisson",
                 E = expected,
                 control.compute = list(config = TRUE))


```

```{r type_II_fit}

# creating constraint matrix needed for Type II Interaction
A <- matrix(0, nrow = n, ncol = n * T)
for (i in 1:n) { 
  A[i, which((1:(n * T))%%n == i - 1)] <- 1
}

# specify constraints in INLA-ready format
constr.st <- list(A = A, e = rep(0, dim(A)[1]))

### defining Kronecker product for the Type II Interaction

# Kronecker product between RW1 and IID space term
# order matters here! In our data set, the time ordering take precedent over the space ordering
# so we must have the RW on the left and space on the right
# Optionally, we scale the matrix beforehand as well
scaled_RW_prec <- inla.scale.model(prec_RW1, list(A = matrix(1, 1, dim(prec_RW1)[1]), e = 0))
R <- scaled_RW_prec %x% diag(n)


# Add Type I Interaction term to basic linear predictor
#Assuming fully connected adjacency structure (e.g no islands) 
#when defining rank-deficiency
lin_pred_w_type_II <- update(basic_linear_predictor, ~. + 
                              f(spacetime.unstructured,
                                model = "generic0", 
                                Cmatrix = R,
                                extraconstr = constr.st, 
                                rankdef = n, 
                                param = c(1, 0.01)))


type_II_fit <- inla(lin_pred_w_type_II,
                 data = ohio_df,
                 family = "poisson",
                 E = expected,
                 control.compute = list(config = TRUE))


```

```{r type_III}
A <- matrix(0, nrow = T, ncol = n * T)
for (i in 1:T) {
  # The ICAR at each time point needs to sum to 1
  A[i, ((i - 1) * n + 1):(i * n)] <- 1
}

scaled_ICAR_prec <- INLA::inla.scale.model(K_theta, 
                                           constr = list(A = matrix(1, 1, dim(K_theta)[1]), e = 0))

R <- diag(T) %x% K_theta 

# specify constraints in INLA-ready format
constr.st <- list(A = A, e = rep(0, dim(A)[1]))

lin_pred_w_type_III <- update(basic_linear_predictor, ~. + f(spacetime.unstructured, 
                                          model = "generic0",
                                          Cmatrix = R,
                                          extraconstr = constr.st, 
                                          rankdef = T, 
                                          param = c(1, 0.01)))


type_III_fit <- inla(lin_pred_w_type_III,
                 data = ohio_df,
                 family = "poisson",
                 E = expected,
                 control.compute = list(config = TRUE))

```

```{r Type_IV}
# Specifying constraints needed for Type IV Interaction
time_constr <- matrix(0, n, n * T)
for (i in 1:n) {
  time_constr[i, which((1:(n * T))%%n == i - 1)] <- 1
}
space_constr <- matrix(0, T-1, n * T)
# theoretically it's enough to only go through N-1 here
# note that we could have instead done 1:(S-1) in the first loop and 1:N in the second
for (i in 1:(T-1)) { 
  space_constr[i, ((i - 1) * n + 1):(i * n)] <- 1
}

# N * S - (N - 1) * (S - 1) = N + S - 1

tmp <- rbind(time_constr, space_constr) 
constr.st <- list(A = tmp, e = rep(0, dim(tmp)[1]))

# Kronecker product between ICAR x RW1
R <- scaled_RW_prec %x% scaled_ICAR_prec

lin_pred_w_type_IV <- update(basic_linear_predictor, ~. + f(spacetime.unstructured, 
                                         model = "generic0",
                                         Cmatrix = R,
                                         extraconstr = constr.st,
                                         rankdef = n + T - 1, 
                                         param = c(1, 0.01)))

type_IV_fit <- inla(lin_pred_w_type_IV,
                 data = ohio_df,
                 family = "poisson",
                 E = expected,
                 control.compute = list(config = TRUE))

```

```{r}
summary(type_IV_fit)

```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```




